module.exports = {
    GENDER_MAN: 1,
    GENDER_WOMAN: 2,
    GRADE_USER: 0,
    GRADE_MANAGER: 1,
    GRADE_SYSTEM_ADMIN: 9,
    ABUNDANCE_RATE_LIST: [
        'None',
        '코롱',
        '오 드 코롱',
        '오 드 뚜왈렛',
        '오 드 퍼퓸',
        '퍼퓸',
        '기타',
    ],
    NOTE_TYPE_TOP: 1,
    NOTE_TYPE_MIDDLE: 2,
    NOTE_TYPE_BASE: 3,
    NOTE_TYPE_SINGLE: 4,
    SEASONAL_LIST: ['None', 'spring', 'summer', 'fall', 'winter'],
    SILLAGE_LIST: ['None', 'light', 'medium', 'heavy'],
    LONGEVITY_LIST: [
        'None',
        'veryWeak',
        'weak',
        'normal',
        'strong',
        'veryStrong',
    ],
    GENDER_LIST: ['None', 'male', 'neutral', 'female'],
    NOTE_TYPE_LIST: ['None', 'top', 'middle', 'base', 'single'],
    PERFUME_NOTE_TYPE_SINGLE: 1,
    PERFUME_NOTE_TYPE_NORMAL: 0,
    MIN_SCORE: 0,
    MAX_SCORE: 10,
    DEFAULT_REVIEW_THRESHOLD: 50,
};
