---
basePath: /A.fume/api/0.0.1
tags:
- name: perfume
  description: 향수 정보
- name: series
  description: 계열
- name: ingredient
  description: 향료
- name: brand
  description: 브랜드
- name: review
  description: 시향기
- name: reply
  description: 댓글
- name: keyword
  description: 키워드
- name: user
  description: 사용자
- name: WEB_perfume
  description: 향수 정보 for Web
- name: WEB_series
  description: 계열 for Web
- name: WEB_ingredient
  description: 향료 for Web
- name: WEB_note
  description: 노트 for Web
- name: WEB_brand
  description: 브랜드 for Web
- name: WEB_user
  description: 사용자 for Web
- name: WEB_keyword
  description: 키워드 for Web

schemes:
#- https
- http
security:
- userToken: []
securityDefinitions:
  userToken:
      type: apiKey
      name: x-access-token
      in: header
      description: /Bearer {token}/ 를 입력해주시면 됩니다.
  APIKeyHeader:
    type: apiKey
    name: X-API-Key
    in: header
externalDocs:
  description: Afume Server Git Wiki
  url: https://github.com/A-fume/A.fume.Server/wiki
