name: Execute Mocha Integral Test

on:
    pull_request:
        branches: [dev, main, production-1, production-2]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
            - run: sh ./script/setup-global.sh
            - run: sh ./script/prebuild.sh
            - name: run integral test code
              run: npm run test-integral
              env:
                  NODE_ENV: production
                  MYSQL_PRD_USERNAME: '${{ secrets.MYSQL_PRD_USERNAME }}'
                  MYSQL_PRD_PASSWORD: '${{ secrets.MYSQL_PRD_PASSWORD }}'
                  MYSQL_PRD_DATABASE: '${{ secrets.MYSQL_PRD_DATABASE }}'
                  MYSQL_PRD_HOST: '${{ secrets.MYSQL_PRD_HOST }}'
                  MYSQL_PRD_PORT: '${{ secrets.MYSQL_PRD_PORT }}'
                  MYSQL_PRD_DIALECT: '${{ secrets.MYSQL_PRD_DIALECT }}'
                  MONGO_URI: '${{ secrets.MONGO_URI }}'
                  CORS_ALLOW_LIST: '${{ secrets.CORS_ALLOW_LIST }}'
                  JWT_SECRET: '${{ secrets.JWT_SECRET }}'
                  ENCRYPTION_KEY: '${{ secrets.ENCRYPTION_KEY }}'
                  ENCRYPT_ALGORITHM: '${{ secrets.ENCRYPT_ALGORITHM }}'
                  TEST_ACCOUNT_ID: '${{ secrets.TEST_ACCOUNT_ID }}'
                  TEST_ACCOUNT_PWD: '${{ secrets.TEST_ACCOUNT_PWD }}'
                  AWS_S3_URL: '${{ secrets.AWS_S3_URL }}'
                  AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
                  AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
                  # TODO: These environments will be removed after detaching afume(previous) bucket
                  AWS_S3_URL_LEGACY: '${{ secrets.AWS_S3_URL_LEGACY }}'
                  AWS_ACCESS_KEY_ID_LEGACY: '${{ secrets.AWS_ACCESS_KEY_ID_LEGACY }}'
                  AWS_SECRET_ACCESS_KEY_LEGACY: '${{ secrets.AWS_SECRET_ACCESS_KEY_LEGACY }}'
                  REDIS_HOST: '${{ secrets.REDIS_HOST }}'
                  REDIS_PORT: '${{ secrets.REDIS_PORT }}'
                  REDIS_DB_ID: '${{ secrets.REDIS_PRD_DB_ID }}'
